### ISSUE TITLE
CloudinaryImageType not compatible with babel-node

### ISSUE THREAD

**Issue by Twansparant** [internetErik/keystone4-universal-react#6]
Hi there,

Thanks for your boilerplate, I'm using it as a base for my project.
I bumped into an issue when I tried to use the **CloudinaryImage** as a field type in one of my models. However it seems it's not working with the current **babel-node** setup.

It's throwing the following error: 

```javascript
/path/to/my/project/node_modules/keystone/fields/types/cloudinaryimage/CloudinaryImageType.js:59
		throw new Error(
		^

Error: Invalid Configuration

CloudinaryImage fields (MyModel.heroImage) require the "cloudinary config" option to be set.

See http://keystonejs.com/docs/configuration/#services-cloudinary for more information.

    at new cloudinaryimage (/path/to/my/project/node_modules/keystone/fields/types/cloudinaryimage/CloudinaryImageType.js:59:9)
    at List.field (/path/to/my/project/node_modules/keystone/lib/list/field.js:45:14)
    at List.<anonymous> (/path/to/my/project/node_modules/keystone/lib/list/add.js:41:16)
    at List.<anonymous> (/path/to/my/project/node_modules/keystone/lib/list/add.js:30:5)
    at /path/to/my/project/node_modules/keystone/lib/list/add.js:74:5
    at arrayEach (/path/to/my/project/node_modules/keystone/node_modules/lodash/lodash.js:537:11)
    at Function.forEach (/path/to/my/project/node_modules/keystone/node_modules/lodash/lodash.js:9359:14)
    at List.add (/path/to/my/project/node_modules/keystone/lib/list/add.js:48:4)
    at Object.<anonymous> (/path/to/my/project/server/models/MyModel.js:12:11)
    at Module._compile (module.js:660:30)
    at loader (/path/to/my/project/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/path/to/my/project/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/path/to/my/project/server/data/objects.js:3:1)
    at Module._compile (module.js:660:30)
    at loader (/path/to/my/project/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/path/to/my/project/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:573:32)
```

I checked the `cloudinary config` and I'm 100% sure it's valid:
```
keystone.init({
	'cloudinary config': process.env.CLOUDINARY_URL || 'cloudinary://333779167276662:_8jbSi9FB3sWYrfimcl8VKh34rI@keystone-demo',
});
```

On further research I found out these lines in `server/index.js` are causing the problem:

```javascript
import routes from './routes';
keystone.set('routes', routes);
```
If I change this to:
```javascript
keystone.set('routes', require('./routes'));
```
The error goes away and my CloudinaryImage field works, but then my routes are not working anymore.

Any idea if there's a workaround for this or is this something keystone should fix?
Thanks!

**Comment by Twansparant** [comment]
Just cloned you repo again and I see in your **Post** model the **CloudinaryImage** field IS working? Very confused where my error is coming from...

**Comment by internetErik** [comment]
Do you mean that you cloned the project again, and setup a cloudinary config, and then it started working?

To be honest, I'm not sure if it's working with CloudinaryImage right now, but I can give it a shot and see - hopefully soon.

**Comment by Twansparant** [comment]
> Do you mean that you cloned the project again, and setup a cloudinary config, and then it started working?

Yes, I cloned your repo again and set my `cloudinary config` accordingly in it and at least your repo works with CloudinaryImage. But in my repo it gives an error, but that has something to do with the loading order of the models.

In one of my api data functions I need to import the model with the **CloudinaryImage** field. Right now I have this in **server/data/posts.js**:

```javascript
'use strict';
import keystone from 'keystone';
import '../models/Post';

const Post = keystone.list('Post');

// do something with the Post list
```

This results in the given error...
Strange?

**Comment by Twansparant** [comment]
Never mind, I had to move the `const Post = keystone.list('Post');` inside my function!

**Comment by Elemino** [comment]
Hey there, 

I am getting the same error. Does this mean I am loading my models in the wrong order? I was wondering what the solution is. Cheers! :)

**Comment by internetErik** [comment]
Would it be possible to share a snippet of code that is related to the error?

I think in the case of @Twansparant the issue was that he was referencing the Post model in the body of a file instead of within a function. Since the file was being imported before the Keystone initialization was run.

**Comment by Elemino** [comment]
I got it resolved. In my case I needed to load cloudinary config before the models. Plus I   didn't load dotenv at the top of my file, so values weren't passing through. :)
